package paquete;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author Giancarlo
 */
public class interfaz_grafica1_de_usuario extends javax.swing.JFrame {

    private simulator_binary_tree simulador = new simulator_binary_tree();
    ArrayList<String> L= new ArrayList<String>();
    int b=0;
    int j=0;

    public interfaz_grafica1_de_usuario() {
        initComponents();
        this.inicializar(false);        
        this.pack();
        this.P1.setVisible(false);
        this.P2.setVisible(false);
        this.Label.setVisible(false);
        this.botonTorneo.setVisible(false);
    }

    private void inicializar(boolean enable) {
        this.botonBorrar.setEnabled(enable);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonTorneo = new javax.swing.JButton();
        P2 = new javax.swing.JButton();
        P1 = new javax.swing.JButton();
        botonHojas = new javax.swing.JButton();
        botonIniciar = new javax.swing.JButton();
        Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        impresion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        panel_principal = new javax.swing.JInternalFrame();
        panel_opciones = new javax.swing.JPanel();
        botonInsertar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();

        botonTorneo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonTorneo.setText("Iniciar nuevo Torneo");
        botonTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTorneoActionPerformed(evt);
            }
        });

        P2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2ActionPerformed(evt);
            }
        });

        P1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });

        botonHojas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonHojas.setText("Participantes");
        botonHojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHojasActionPerformed(evt);
            }
        });

        botonIniciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonIniciar.setText("Iniciar Torneo");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });

        Label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Label.setText("Por:");

        jScrollPane1.setOpaque(false);

        impresion.setEditable(false);
        impresion.setColumns(20);
        impresion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        impresion.setRows(5);
        impresion.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados de operaciones"));
        impresion.setOpaque(false);
        jScrollPane1.setViewportView(impresion);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de Pruebas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        jPanel2.setOpaque(false);

        jDesktopPane1.setOpaque(false);

        panel_principal.setBackground(new java.awt.Color(204, 204, 204));
        panel_principal.setIconifiable(true);
        panel_principal.setMaximizable(true);
        panel_principal.setResizable(true);
        panel_principal.setEnabled(false);
        panel_principal.setFocusCycleRoot(false);
        panel_principal.setVisible(true);

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal.getContentPane());
        panel_principal.getContentPane().setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        jDesktopPane1.add(panel_principal);
        panel_principal.setBounds(-20, -10, 700, 350);

        panel_opciones.setBackground(new java.awt.Color(204, 204, 204));
        panel_opciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        panel_opciones.setOpaque(false);

        botonInsertar.setBackground(new java.awt.Color(255, 255, 255));
        botonInsertar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonInsertar.setText("Insertar");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        botonBorrar.setBackground(new java.awt.Color(255, 255, 255));
        botonBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_opcionesLayout = new javax.swing.GroupLayout(panel_opciones);
        panel_opciones.setLayout(panel_opcionesLayout);
        panel_opcionesLayout.setHorizontalGroup(
            panel_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_opcionesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(botonInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_opcionesLayout.setVerticalGroup(
            panel_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_opcionesLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(panel_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(botonInsertar)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(panel_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        try {
            String dato = JOptionPane.showInputDialog("Digite dato entero para borrar: ");
            this.impresion.setText(this.simulador.borrar(dato));
            repintarArbol();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        try {
            String dato = JOptionPane.showInputDialog("Digite dato entero para insertar:");
            if(dato==null || dato.equals("")){
                JOptionPane.showMessageDialog(null, "No se pudo insertar el dato", "Intenta de nuevo...", 0);
                this.impresion.setText("No se pudo insertar el dato");
            }else{
                if (this.simulador.insertar(dato)) {
                    JOptionPane.showMessageDialog(null, "El dato fue insertado correctamente", " ...", 1);
                    this.impresion.setText("El dato fue insertado correctamente");
                }
                this.inicializar(true);
                repintarArbol();                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo insertar el dato", "Intenta de nuevo...", 0);
            this.impresion.setText("No se pudo insertar el dato");

        }
    }//GEN-LAST:event_botonInsertarActionPerformed

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        try {
            int m=JOptionPane.showConfirmDialog(rootPane, "Esta seguro que quiere iniciar el torneo? \n"+
                    "Despues de iniciar no podra agregar ni eliminar participantes.", "Confirmar", JOptionPane.YES_NO_OPTION, WIDTH);    
            
            if (m == JOptionPane.YES_OPTION) {                
                int n=simulador.getN();
                if(n==0){
                    JOptionPane.showMessageDialog(null, "No hay ganador, no hay participantes", "No winner", 0);
                }
                if(n==1){
                    this.botonBorrar.setEnabled(false);
                    this.botonIniciar.setEnabled(false);
                    this.botonInsertar.setEnabled(false);
                    this.botonTorneo.setVisible(true);
                    String w=simulador.getWinner();
                    if(!w.equals("")){
                        JOptionPane.showMessageDialog(null, "El ganador es: "+w, "winner", 1);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "No hay ganador, no hay participantes", "No winner", 0);
                    }
                }
                if(n>1){   
                    this.botonBorrar.setEnabled(false);
                    this.botonIniciar.setEnabled(false);
                    this.botonInsertar.setEnabled(false);
                    j=simulador.getN(); 
                    win();                                
                }
                
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo iniciar torneo", "Intenta de nuevo...", 0);

        }
        
    }//GEN-LAST:event_botonIniciarActionPerformed
    
    private void win(){
        ArrayList<String> T= simulador.getT();               
        int i=j-1;
        if(i==0){            
            this.simulador.win(T.get(i));
            L.add(T.get(i));
            b++; 
            i--;       
            j--;
        }else if(i>0){
            this.P1.setVisible(true);
            this.P2.setVisible(true);
            this.Label.setVisible(true);
            this.P1.setText(T.get(i));
            i--;
            j--;
            this.P2.setText(T.get(i));
            i--;
            j--;
        }
        
        String s=simulador.Tree_arbol_2.getRaiz().getDato();
        if(!s.equals("")){    
            this.botonTorneo.setVisible(true);
            JOptionPane.showMessageDialog(null, "Hay un ganador!!!!"+"\n"+"El ganador es: "+"\n"+s, "Intenta de nuevo...", 1);  
            this.P1.setVisible(false);
            this.P2.setVisible(false);
            this.Label.setVisible(false); 
            b=0;
            L.clear();
        }else if(j==0&&b!=0){  
            simulador.setN(b);
            simulador.setT(L);
            j=simulador.getN();
            b=0;
            L.clear();
            win();
        }
    }
    
    private void botonHojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHojasActionPerformed
        String salida = this.simulador.darHojas();
                this.impresion.setText("");
                this.impresion.setText(salida);
    }//GEN-LAST:event_botonHojasActionPerformed

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed
        simulador.win(this.P1.getText());
        repintarArbol();
        this.P1.setVisible(false);
        this.P2.setVisible(false);
        this.Label.setVisible(false);   
        L.add(this.P1.getText());
        b++;
        win();
    }//GEN-LAST:event_P1ActionPerformed

    private void P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2ActionPerformed
        simulador.win(this.P2.getText());
        repintarArbol();
        this.P1.setVisible(false);
        this.P2.setVisible(false);
        this.Label.setVisible(false);  
        L.add(this.P2.getText());
        b++;
        win();
    }//GEN-LAST:event_P2ActionPerformed

    private void botonTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTorneoActionPerformed
        j=0;
        simulador=new simulator_binary_tree();
        repintarArbol();
        this.botonIniciar.setEnabled(true);
        this.botonInsertar.setEnabled(true);
        this.botonTorneo.setVisible(false);
    }//GEN-LAST:event_botonTorneoActionPerformed
    
    private void repintarArbol() {
        this.jDesktopPane1.removeAll();
        Rectangle tamaño = this.panel_principal.getBounds();
        this.panel_principal = null;
        this.panel_principal = new JInternalFrame("Representación gráfica", true);
        this.jDesktopPane1.add(this.panel_principal, JLayeredPane.DEFAULT_LAYER);
        this.panel_principal.setVisible(true);
        this.panel_principal.setBounds(tamaño);
        this.panel_principal.setEnabled(false);
        this.panel_principal.add(this.simulador.getDibujo(), BorderLayout.CENTER);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_grafica1_de_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_grafica1_de_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_grafica1_de_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_grafica1_de_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_grafica1_de_usuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JButton P1;
    private javax.swing.JButton P2;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonHojas;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonInsertar;
    private javax.swing.JButton botonTorneo;
    private javax.swing.JTextArea impresion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_opciones;
    private javax.swing.JInternalFrame panel_principal;
    // End of variables declaration//GEN-END:variables
}
